### ISSUE TITLE
powerd++ should not set frequency on each core

### ISSUE THREAD

**Issue by delphij** [lonkamikaze/powerdxx#11]
While observing other performance issue on -CURRENT, I noticed a code path in my hwpmc data:

```
 19.57%  [128]       mtrash_ctor
  100.0%  [128]        item_ctor
   100.0%  [128]         malloc
    76.56%  [98]           cpufreq_insert_abs
     100.0%  [98]            cf_levels_method
      100.0%  [98]             cpufreq_curr_sysctl
       100.0%  [98]              sysctl_root_handler_locked
        100.0%  [98]               sysctl_root
         100.0%  [98]                userland_sysctl
          100.0%  [98]                 sys___sysctl
           100.0%  [98]                  amd64_syscall

```
And a quick ktrace over powerd++ suggests that it's performing sysctl on dev.cpu.*.freq for all CPUs.

Note that FreeBSD do not support setting different frequencies for each CPU, this should be changed to set dev.cpu.0.freq only (as it's already doing setting all CPUs internally, see comment in https://svnweb.freebsd.org/base/head/sys/kern/kern_cpu.c?annotate=360464#l957 ).  As the result, the current code would consume CPU exponentially with no benefit.

**Comment by lonkamikaze** [comment]
The issue IMHO is that the kernel offers redundant .freq handles on CURRENT. powerd++ is explicitly built to support per core (or group of cores) frequency handling, assuming that the kernel would one day offer the feature.

If the kernel now offers the interface it should act accordingly, i.e. pre-CURRENT only dev.cpu.0 has a freq handle, because only one frequency can be set.

With hwpstate enabled every pipeline has a .freq handle (instead of every core), which I suspect is false (I don't think pipelines that share an ALU can run at different frequencies). But with hwpstate enabled powerd++ should not be running any way, either due to an assertion, or because hwpstate is blacklisted explicitly (see issue #10).

**Comment by lonkamikaze** [comment]
No more comments received.
