### ISSUE TITLE
(EDRIVER) frequency control driver not supported: hwpstate_intel0

### ISSUE THREAD

**Issue by nunotexbsd** [lonkamikaze/powerdxx#15]
Hello,

I cannot use powerdxx on FreeBSD 14 CURRENT ( cf5d11124 ) on a [Lenovo Legion 5i](https://bsd-hardware.info/?probe=9fed35d792)

It gives the error:
`powerd++: (EDRIVER) frequency control driver not supported: hwpstate_intel0`

Any hints?

Thanks,
Nuno Teixeira

**Comment by lonkamikaze** [comment]
For CPUs that are supported by the hwpstate driver powerd++ is obsolete and in fact not possible, because the driver discards frequencies set via the sysctl interface.

There is a loader tunable that lets you turn it off: `hint.hwpstate_intel.0.disabled`
You can use that if you have issues with hwpstate controlling your CPU frequency.

Would it be better to print a multi-line description explaining this?

**Comment by nunotexbsd** [comment]
Hello!
Sorry for delay.

I've openned a PR at https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=255324

**Comment by lonkamikaze** [comment]
I don't know what to say.

**Comment by nunotexbsd** [comment]
Sorry I didn't understand your action.
Did I said something wrong?

**Comment by nunotexbsd** [comment]
And I'm not an experienced software porter and I'm still learning hoping doing some good job at it.

**Comment by mr44er** [comment]
> Did I said something wrong?

It *DOES NOT WORK* with your CPU *AND* therefore it's obsolete because **hwpstate already does the job**.

He explained it 29 days ago.

**Comment by nunotexbsd** [comment]
Thanks for explanation.
I understand it now.

**Comment by allanjude** [comment]
To try to save you from more people like this, we're adding a section to the handbook, with a relevant link in the 13.0 release notes: https://reviews.freebsd.org/D30004

**Comment by nunotexbsd** [comment]
Nice! I'm following that review and PR https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=253288 too.

Thanks
